language: android

jdk:
  - oraclejdk7

android:
  components:
    - build-tools-23.0.1
    - android-23
    - android-22
    - android-21
    - android-19
    - sys-img-x86-android-19
    - sys-img-x86-android-21
    - sys-img-x86-android-22
    - sys-img-x86-android-23
    - extra-android-m2repository

env:
  global:
    # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

# no caching and admin rights
cache: false
sudo: false

script: ./build.sh

after_failure:
  - cat app/build/reports/androidTests/connected/*.html
  - adb logcat -d
