language: android

jdk:
  - oraclejdk7

android:
  components:
    - build-tools-23.0.1
    - android-23
    - $ANDROID_TARGET
    - extra-android-m2repository
    - $ANDROID_IMAGE

env:
  global:
    # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

  matrix:
    - ANDROID_TARGET=android-19    ANDROID_IMAGE=sys-img-armeabi-v7a-android-19    ANDROID_ABI=armeabi-v7a
    # 20 is just for wearables..
    - ANDROID_TARGET=android-21    ANDROID_IMAGE=sys-img-armeabi-v7a-android-21    ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-22    ANDROID_IMAGE=sys-img-armeabi-v7a-android-22    ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-23    ANDROID_IMAGE=sys-img-armeabi-v7a-android-23    ANDROID_ABI=armeabi-v7a

# no
cache: false
sudo: false

before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI --skin WXGA720
  - emulator -avd test -no-audio -no-window -gpu off &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script: gradle build connectedCheck

after_success:
  - gradle coveralls

after_failure:
  - cat app/build/reports/androidTests/connected/*.html
  - adb logcat -d
